import { db } from '../src/config/firebase';
import { collection, addDoc } from 'firebase/firestore';

const courses = [
  {
    title: 'Russe Débutant',
    description: 'Commencez à apprendre le russe de zéro avec des bases solides.',
    level: 'beginner',
    category: 'Général',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 12,
    estimatedTime: 90,
    tags: ['alphabet', 'bases', 'débutant'],
    isCompleted: false,
    progress: 0,
    rating: 4.7,
    enrolledCount: 1200,
  },
  {
    title: 'Conversation courante',
    description: 'Apprenez à tenir une conversation simple en russe.',
    level: 'beginner',
    category: 'Conversation',
    imageUrl: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 10,
    estimatedTime: 75,
    tags: ['conversation', 'débutant'],
    isCompleted: false,
    progress: 0,
    rating: 4.5,
    enrolledCount: 950,
  },
  {
    title: 'Grammaire intermédiaire',
    description: 'Maîtrisez les points clés de la grammaire russe.',
    level: 'intermediate',
    category: 'Grammaire',
    imageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 15,
    estimatedTime: 120,
    tags: ['grammaire', 'intermédiaire'],
    isCompleted: false,
    progress: 0,
    rating: 4.6,
    enrolledCount: 800,
  },
  {
    title: 'Russe avancé',
    description: 'Perfectionnez votre russe avec des textes et dialogues complexes.',
    level: 'advanced',
    category: 'Littérature',
    imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 18,
    estimatedTime: 150,
    tags: ['avancé', 'littérature'],
    isCompleted: false,
    progress: 0,
    rating: 4.8,
    enrolledCount: 500,
  },
  {
    title: 'Vocabulaire thématique',
    description: 'Enrichissez votre vocabulaire par thèmes (voyage, travail, famille...).',
    level: 'intermediate',
    category: 'Vocabulaire',
    imageUrl: 'https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 14,
    estimatedTime: 100,
    tags: ['vocabulaire', 'intermédiaire'],
    isCompleted: false,
    progress: 0,
    rating: 4.4,
    enrolledCount: 700,
  },
  // Modules supplémentaires
  {
    title: 'Prononciation russe',
    description: 'Travaillez votre accent et la prononciation des sons difficiles.',
    level: 'beginner',
    category: 'Prononciation',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 8,
    estimatedTime: 60,
    tags: ['prononciation', 'écoute'],
    isCompleted: false,
    progress: 0,
    rating: 4.3,
    enrolledCount: 600,
  },
  {
    title: 'Conjugaison facile',
    description: 'Apprenez à conjuguer les verbes russes aux temps principaux.',
    level: 'beginner',
    category: 'Conjugaison',
    imageUrl: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 9,
    estimatedTime: 70,
    tags: ['conjugaison', 'verbes'],
    isCompleted: false,
    progress: 0,
    rating: 4.2,
    enrolledCount: 550,
  },
  {
    title: 'Compréhension orale',
    description: 'Développez votre compréhension de l’oral avec des dialogues et podcasts.',
    level: 'intermediate',
    category: 'Compréhension orale',
    imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 11,
    estimatedTime: 85,
    tags: ['écoute', 'audio'],
    isCompleted: false,
    progress: 0,
    rating: 4.5,
    enrolledCount: 400,
  },
  {
    title: 'Écriture et dictées',
    description: 'Améliorez votre écriture et votre orthographe avec des dictées et exercices.',
    level: 'intermediate',
    category: 'Écriture',
    imageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 10,
    estimatedTime: 80,
    tags: ['écriture', 'dictée'],
    isCompleted: false,
    progress: 0,
    rating: 4.1,
    enrolledCount: 350,
  },
  {
    title: 'Culture et civilisation',
    description: 'Découvrez la culture russe à travers l’histoire, la géographie et les traditions.',
    level: 'advanced',
    category: 'Culture',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 13,
    estimatedTime: 110,
    tags: ['culture', 'civilisation'],
    isCompleted: false,
    progress: 0,
    rating: 4.6,
    enrolledCount: 300,
  },
  {
    title: 'Lecture de textes',
    description: 'Lisez et analysez des textes russes authentiques pour progresser.',
    level: 'advanced',
    category: 'Lecture',
    imageUrl: 'https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=600&q=80',
    lessonsCount: 12,
    estimatedTime: 95,
    tags: ['lecture', 'analyse'],
    isCompleted: false,
    progress: 0,
    rating: 4.7,
    enrolledCount: 250,
  },
];

export async function seedCourses() {
  for (const course of courses) {
    await addDoc(collection(db, 'courses'), course);
    console.log(`Ajouté : ${course.title}`);
  }
  console.log('Tous les cours ont été ajoutés !');
}

// Pour exécuter dans l'app :
// import { seedCourses } from '../scripts/seedCoursesApp';
// seedCourses();
